apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asteroid-detector
  template:
    metadata:
      labels:
        app: asteroid-detector
    spec:
      containers:
      - name: asteroid-detector
        image: {{ .Values.detector.image}}
        command: ["node", "/app/asteroid-detector.js"]
        volumeMounts:
        - name: app-code
          mountPath: /app
          readOnly: true
        env:
        - name: NODE_ENV
          value: "production"
        - name: SCANNING_LOCATION
          valueFrom:
            configMapKeyRef:
              key: scanning_location
              name: {{ .Rele.Name }}-config
        resources:
          requests:
            cpu: {{ .Values.detector.resources.requests.cpu }}
            memory: {{ .Values.detector.resources.requests.memory }}
          limits:
            cpu: {{ .Values.detector.resources.limits.cpu }}
            memory: {{ .Values.detector.resources.limits.memory }}
      volumes:
      - name: app-code
        configMap:
          name: {{ .Release.Name }}-app-code
