apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: gravity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gravitational-accelerator
  template:
    metadata:
      labels:
        app: gravitational-accelerator
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $ps := . }}
      - name: {{ $ps }}
      {{- end }}
      {{- end }}
      containers:
      - name: gravitational-accelerator
        image: {{ .Values.accelerator.image }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir node && cd node && cp /app/gravitational-accelerator.js . &&
            npm install @opentelemetry/api \
              @opentelemetry/sdk-node \
              @opentelemetry/instrumentation-http \
              @opentelemetry/auto-instrumentations-node \
              @opentelemetry/exporter-prometheus &&
            node gravitational-accelerator.js
        env:
        - name: MAINTENANCE_MODE
          value: "false"
        - name: OTEL_EXPORTER_PROMETHEUS_PORT
          value: "9464"
        resources:
          requests:
            memory: {{ .Values.accelerator.resources.requests.memory }}
            cpu: {{ .Values.accelerator.resources.requests.cpu }}
          limits:
            memory: {{ .Values.accelerator.resources.limits.memory }}
            cpu: {{ .Values.accelerator.resources.limits.cpu }}
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        configMap:
          name: {{ .Release.Name }}-code
