apiVersion: v2
name: gravitational-accelerator
description: A Helm chart for the Gravitational Accelerator application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Jeroen van Erp
    email: jeroen@geeko.me
keywords:
  - gravity
  - helm
